[package]
name = "hooks"
version = "0.1.0"
edition = "2021"

authors = ["SunStorm"]
license = "AGPL-3.0-only"
license-file = "LICENSE"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
